// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kernel_change_point_cpp
Rcpp::List kernel_change_point_cpp(const Eigen::MatrixXd& X, std::string kernel, double sigma, int Dmax, double Cpen, double vmax, int rank, double t_left, double t_right, bool verbose);
RcppExport SEXP _M2DSAlgoProject_kernel_change_point_cpp(SEXP XSEXP, SEXP kernelSEXP, SEXP sigmaSEXP, SEXP DmaxSEXP, SEXP CpenSEXP, SEXP vmaxSEXP, SEXP rankSEXP, SEXP t_leftSEXP, SEXP t_rightSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type Dmax(DmaxSEXP);
    Rcpp::traits::input_parameter< double >::type Cpen(CpenSEXP);
    Rcpp::traits::input_parameter< double >::type vmax(vmaxSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    Rcpp::traits::input_parameter< double >::type t_left(t_leftSEXP);
    Rcpp::traits::input_parameter< double >::type t_right(t_rightSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_change_point_cpp(X, kernel, sigma, Dmax, Cpen, vmax, rank, t_left, t_right, verbose));
    return rcpp_result_gen;
END_RCPP
}
// dp_changepoint_cpp
Rcpp::List dp_changepoint_cpp(const Eigen::VectorXd& data, double beta);
RcppExport SEXP _M2DSAlgoProject_dp_changepoint_cpp(SEXP dataSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(dp_changepoint_cpp(data, beta));
    return rcpp_result_gen;
END_RCPP
}
// dp_changepoint_pelt_cpp
Rcpp::List dp_changepoint_pelt_cpp(const Eigen::VectorXd& data, double beta);
RcppExport SEXP _M2DSAlgoProject_dp_changepoint_pelt_cpp(SEXP dataSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(dp_changepoint_pelt_cpp(data, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_M2DSAlgoProject_kernel_change_point_cpp", (DL_FUNC) &_M2DSAlgoProject_kernel_change_point_cpp, 10},
    {"_M2DSAlgoProject_dp_changepoint_cpp", (DL_FUNC) &_M2DSAlgoProject_dp_changepoint_cpp, 2},
    {"_M2DSAlgoProject_dp_changepoint_pelt_cpp", (DL_FUNC) &_M2DSAlgoProject_dp_changepoint_pelt_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_M2DSAlgoProject(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
