# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernel_change_point_cpp <- function(X, kernel = "rbf", sigma = -1.0, Dmax = 50L, Cpen = 2.0, vmax = -1.0, rank = -1L, t_left = 0.05, t_right = 0.95, verbose = TRUE) {
    .Call(`_M2DSAlgoProject_kernel_change_point_cpp`, X, kernel, sigma, Dmax, Cpen, vmax, rank, t_left, t_right, verbose)
}

dp_changepoint_cpp <- function(data, beta) {
    .Call(`_M2DSAlgoProject_dp_changepoint_cpp`, data, beta)
}

dp_changepoint_pelt_cpp <- function(data, beta) {
    .Call(`_M2DSAlgoProject_dp_changepoint_pelt_cpp`, data, beta)
}

rcpp_hello <- function() {
    .Call(`_M2DSAlgoProject_rcpp_hello`)
}

